### ISSUE TITLE
What are the main features the user must be introduced to?

### ISSUE THREAD

**Issue by davidpobi** [aycarl/notices#1]
## Description
- How does the average user interact with news items or updates in Ashesi University? 
- Which platform or framework will be used? 
## Enhancements
- create a simple user interface containing four categories of news
- allow all users to edit the lost and found list category 
- each category should be expandable to view more details
## Test
- Functionality tests on features implemented 
- Jasmine, curl, or which ever testing process should be employed

**Comment by yao-carl** [comment]
![img_20150930_080553](https://cloud.githubusercontent.com/assets/4999487/10187988/9a5c02f4-674b-11e5-92c8-a94d0c30dffd.jpg)
![img_20150930_080605](https://cloud.githubusercontent.com/assets/4999487/10187992/9d28f8f2-674b-11e5-9ac7-0032ffba4ae9.jpg)
![img_20150930_080619](https://cloud.githubusercontent.com/assets/4999487/10187994/9ed9e62a-674b-11e5-940e-0ac22e00fb6e.jpg)

**Comment by aycarl** [comment]
.
